export const ROUTES = {
  HOME: '/home',
  LOGIN: '/login',
  CART: '/cart',
  EDIT_USER_INFO: '/edit-user-info',
  MY_PRODUCT_REVIEW: '/my-product-review',
  MYPAGE: '/mypage',
  ORDER: '/order',
  ORDER_HISTORY: '/order-history',
  PAYMENT_HISTORY: '/payment-history',
  PRODUCT_LIST: '/product-list',
  REVIEW_WRITE: '/review-write',
  SIGN_UP: '/sign-up',
  SIGN_UP_DONE: '/sign-up-done',
  WITHDRAW: '/withdraw',
} as const;
